### PR TITLE
Global Customizations: Allow to remove an uploaded image

### LINKED ISSUE #1036: Global Customizations: Allow to remove an uploaded background image and studio logo
## Story

When a Global Customization logo or background image is uploaded, you can't remove it - you can only upload replacement images.

### To reproduce

1. Upload an image
2. You can't remove it.

### Expected behavior

Allow to clear the upload using some dedicated button.

## Environment

- **Server version**: 1.7.2
- **Server host OS**:
- **Browser**:  Firefox + Chrome
- **Client version**:

### PR DESCRIPTION
**Pull request by BigRoy**
## Description of changes 

Toggle the upload component to "Remove" button if it currently contains an uploaded file so that you can remove things.

## Technical details

@Innders visually it looks good - but I can't get the _clear_ to actually influence the stored result. So when refreshing you can see it never actually 'cleared' anything.

- [x] Fix persisting removal.

Fix #1036

## Additional context

image
image

### CODE REVIEW

File: src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx [hunk 1]
```diff
@@ -84,13 +84,22 @@ const ServerConfigUpload: FC<ServerConfigUploadProps> = ({ fileType, fileName, s
     inputRef.current?.click()
   }
 
+  const handleClear = () => {
+    setFileName("")
```
Comment (Innders) [inline src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx:88]: This is just a local state and won't mutate the data on the server.

1. Add a new prop to this component `onClear: () => void`.
2. Replace setFileName with onClear().
3. Handle onClear in https://github.com/ynput/ayon-frontend/blob/ed7bef93bf7d8c7d2b7b12cbc3845edeeb05943a/src/pages/SettingsPage/ServerConfig/ServerConfig.tsx
4. top level clear handler does something basically like this.

```tsx
  const handleClearUpload = async (field: 'login_background' | 'studio_logo') => {
    try {
      // clear the filename in the formData and update the server config
      // local fileName state will be updated by the useEffect above
      await setServerConfig({
        serverConfigModel: {
          ...formData,
          customization: {
            ...formData.customization,
            [field]: '',
          },
        },
      }).unwrap()
    } catch (error) {
      toast.error('Failed to clear upload')
    }
  }
```

**Review by Innders — CHANGES_REQUESTED** [review]
I like the button switching now just need to connect the pipes.

File: src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx [hunk 2]
```diff
@@ -87,10 +88,15 @@ const ServerConfigUpload: FC<ServerConfigUploadProps> = ({ fileType, fileName, s
   return (
     <UploadContainer>
       <Filename>{fileName}</Filename>
-
-      <Button icon={loading ? 'sync' : 'upload'} onClick={handleButtonClick}>
-        Upload
-      </Button>
+      {fileName ? (
```
Comment (Innders) [inline src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx:91]: Could we please have a consistent width of the buttons. I would go for 100px.

image

**Review by Innders — CHANGES_REQUESTED** [review]
Logic works great, just one small cosmetic issue.

File: src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx (hunk 2 above)
Comment (BigRoy) [reply src/pages/SettingsPage/ServerConfig/ServerConfigUpload.tsx:95]: Is this fine @Innders ? https://github.com/ynput/ayon-frontend/pull/1039/commits/b67ae27c0a35f138f712c979205761486cd2618e

image

**Review by Innders — APPROVED** [review]
Great stuff, thanks @BigRoy !
